/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as AuthStatsRouteImport } from './routes/_auth.stats'
import { Route as AuthSettingsRouteImport } from './routes/_auth.settings'
import { Route as AuthListsRouteImport } from './routes/_auth.lists'
import { Route as AuthItemsRouteImport } from './routes/_auth.items'
import { Route as AuthGenerateRouteImport } from './routes/_auth.generate'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStatsRoute = AuthStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthListsRoute = AuthListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AuthRoute,
} as any)
const AuthItemsRoute = AuthItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGenerateRoute = AuthGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/generate': typeof AuthGenerateRoute
  '/items': typeof AuthItemsRoute
  '/lists': typeof AuthListsRoute
  '/settings': typeof AuthSettingsRoute
  '/stats': typeof AuthStatsRoute
  '/auth/confirm': typeof AuthConfirmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/generate': typeof AuthGenerateRoute
  '/items': typeof AuthItemsRoute
  '/lists': typeof AuthListsRoute
  '/settings': typeof AuthSettingsRoute
  '/stats': typeof AuthStatsRoute
  '/auth/confirm': typeof AuthConfirmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_auth/generate': typeof AuthGenerateRoute
  '/_auth/items': typeof AuthItemsRoute
  '/_auth/lists': typeof AuthListsRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/stats': typeof AuthStatsRoute
  '/auth/confirm': typeof AuthConfirmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/generate'
    | '/items'
    | '/lists'
    | '/settings'
    | '/stats'
    | '/auth/confirm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/generate'
    | '/items'
    | '/lists'
    | '/settings'
    | '/stats'
    | '/auth/confirm'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/login'
    | '/_auth/generate'
    | '/_auth/items'
    | '/_auth/lists'
    | '/_auth/settings'
    | '/_auth/stats'
    | '/auth/confirm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/stats': {
      id: '/_auth/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthStatsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/lists': {
      id: '/_auth/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof AuthListsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/items': {
      id: '/_auth/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AuthItemsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/generate': {
      id: '/_auth/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AuthGenerateRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthGenerateRoute: typeof AuthGenerateRoute
  AuthItemsRoute: typeof AuthItemsRoute
  AuthListsRoute: typeof AuthListsRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthStatsRoute: typeof AuthStatsRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthGenerateRoute: AuthGenerateRoute,
  AuthItemsRoute: AuthItemsRoute,
  AuthListsRoute: AuthListsRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthStatsRoute: AuthStatsRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  AuthConfirmRoute: AuthConfirmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
